### ISSUE TITLE
Add block color column on blocks table

### ISSUE THREAD

**Issue by livemixlove** [trilliumtransit/migrate-GTFS#10]
@ed-g

**Comment by ed-g** [comment]
@livemixlove Would you also like a text color, similar to GTFS spec:

https://developers.google.com/transit/gtfs/reference#routes_route_color_field

**Comment by ed-g** [comment]
Will this be hex, `0xRRGGBB` or a human text such as 'yellow'?

**Comment by livemixlove** [comment]
Both! Or if we have to pick, hex.

**Comment by ed-g** [comment]
Is the color a css color? Just thinking about how we can validate values.

**Comment by livemixlove** [comment]
Yes, css color.

**Comment by ed-g** [comment]
cool, I've added color with validator based on https://github.com/jnikles/css-color-validator/blob/master/lib/isValidColor.js

**Comment by ed-g** [comment]
rather, these are on migrate_blocks in GTFSManager database, and will add to WakeRobin schema shortly.

**Comment by ed-g** [comment]
7a03f67
