### ISSUE TITLE
Give patterns names

### ISSUE THREAD

**Issue by antrim** [trilliumtransit/migrate-GTFS#11]
**Proposal:** We will implement a naming scheme in the migrate process. We will assess its viability afterwards. This may end up being an interim scheme.

**Scheme:**
* Pattern that is most-used in the schedule is called "Primary"
* All other patterns are named by their deviation from the primary. So the 10AM - PM AMRTS service (https://gtfs.trilliumtransit.com/trip_dashboard.php?trip_id=123454&agency_id=3) would be "+ Community Center". If stops are removed (compared to primary), then this is indicated by minus ("-").
* Up to 3 added stops are shown, and three removed stops. If the numbers are greater then we just see a number, e.g. "+ 4 stops"

**Comment by ed-g** [comment]
Just to clarify, we are first grouping patterns by their route when assigning names?

**Comment by antrim** [comment]
Patterns will always be grouped by route in the UI. So pattern names only
need to be unique per route.

On Tue, Jul 12, 2016 at 12:12 PM, Ed Groth <notifications@github.com> wrote:

> Just to clarify, we are first grouping patterns by their route when
> assigning names?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/trilliumtransit/migrate-GTFS/issues/11#issuecomment-232149119>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGMdl3JEAKTcJYgi9Kd8yq6jiRYK8qvHks5qU-cjgaJpZM4JJqrG>
> .
>



-- 
Aaron Antrim, Principal
Trillium Solutions, Inc.
www.trilliumtransit.com
Portland, Oregon
503.567.8422 ext. 3

**Comment by ed-g** [comment]
Updated play_migrate_patterns with this naming convention.

Note that some patterns appear to have the same set of stops as the Primary but in a different order, or with multiple visits to the same stop. These have the name "+ 0 stops - 0 stops" which is a little confusing. We might want to think about how to name this edge case.

```sql
WITH

patterns_with_stops_difference AS 
(select
    p.route_id, p.pattern_id, primary_pattern_id  
  , array_length(s_agg.stop_ids, 1) as n_stops
  , coalesce(array_length(s_agg.stop_ids - primary_s_agg.primary_stop_ids, 1), 0) as n_added_stops
  , coalesce(array_length(primary_s_agg.primary_stop_ids - s_agg.stop_ids, 1), 0) as n_removed_stops
  , s_agg.stop_ids - primary_s_agg.primary_stop_ids as added_stop_ids
  , primary_s_agg.primary_stop_ids - s_agg.stop_ids as removed_stop_ids
  , s_agg.stop_ids
from play_migrate_patterns p
join views.play_migrate_route_primary_patterns using (route_id)
join
    ( select pattern_id, array_agg(stop_id order by stop_id) stop_ids
      from play_migrate_pattern_stops group by pattern_id) s_agg
    using (pattern_id)
join
    ( select pattern_id, array_agg(stop_id order by stop_id) primary_stop_ids
      from play_migrate_pattern_stops group by pattern_id) primary_s_agg
    on (primary_s_agg.pattern_id = play_migrate_route_primary_patterns.primary_pattern_id)  )

,generated_names AS
(select
    route_id
  , pattern_id
  , primary_pattern_id
  , n_added_stops
  , n_removed_stops
  , case when pattern_id = primary_pattern_id 
        then 'Primary' 
        else case when (n_added_stops > 3 or n_added_stops = 0)
                 then '+ ' || n_added_stops || ' stops'
                 else '+ ' || (select string_agg(stop_name, ' + ') from  play_migrate_stops where stop_id   in (select unnest(added_stop_ids))) end
          || case when (n_removed_stops > 3 or n_removed_stops = 0)
                 then ' - ' || n_removed_stops || ' stops'
                 else ' - ' || (select string_agg(stop_name, ' - ') from  play_migrate_stops where stop_id   in (select unnest(removed_stop_ids))) end
        end
   as generated_name
from patterns_with_stops_difference
order by route_id, pattern_id)

update play_migrate_patterns SET name = generated_name
from generated_names
where generated_names.pattern_id = play_migrate_patterns.pattern_id
```

**Comment by ed-g** [comment]
Group by both route_id and direction_id before assigning names.

**Comment by ed-g** [comment]
@livemixlove patterns are now grouped by both route_id and direction_id before assigning a primary and deviants.
