### ISSUE TITLE
Add name column to patterns table

### ISSUE THREAD

**Issue by livemixlove** [trilliumtransit/migrate-GTFS#12]
@ed-g

**Comment by ed-g** [comment]
Assign a name.

For now, assign the name based on the first stop in the pattern, the last stop in the pattern, and the number of stops.

**Comment by ed-g** [comment]
https://github.com/trilliumtransit/migrate-GTFS/commit/8d566e46a41fbd7cb861adb3e7e8c49bd0e8b7bd
