### ISSUE TITLE
Fares

### ISSUE THREAD

**Issue by antrim** [trilliumtransit/migrate-GTFS#2]

**Comment by ed-g** [comment]
77af20f8a8fc66eecb36698e5bf787e75e1a4a2b

**Comment by antrim** [comment]
Commit 7f12c46d3544feddfa54c7c50edbe2c7693a6d63 adds two new fields to support Wake Robin v1 fare features (see UI sketch, https://docs.google.com/drawings/d/11pgz1Zmr8i04tMHKI13U5uCu8TRYOn47IjngX8O8DwE/edit). The two new fields are fare_rules.reversible and fare_rules.combinable.

Let's focus on **reversible**. When active, this means that an origin/destination zone fare rule is true in reverse order.

So we need to identify these cases during the migration. Ed, can you add this?

Below shows fare rules where there is a DIFFERENT reverse direction fare. More at https://3.basecamp.com/3194913/buckets/257018/todos/149854143#__recording_151391437

```sql
select rules_x.fare_rule_id,rules_x.fare_id,rules_x.origin_id,rules_x.destination_id,rules_x.agency_id,agency.agency_name,z1.zone_name AS origin_zone, z2.zone_name AS destination_zone, fare_attributes.price, f1.price as opposite_fare
from fare_rules rules_x
LEFT JOIN fare_rules rules_y
on (rules_x.origin_id = rules_y.destination_id AND rules_x.destination_id = rules_y.origin_id AND rules_x.fare_id = rules_y.fare_id)

INNER JOIN zones z1 ON rules_x.origin_id = z1.zone_id
INNER JOIN zones z2 ON rules_x.destination_id = z2.zone_id

left JOIN fare_rules rules_opposite
ON (rules_x.origin_id = rules_opposite.destination_id AND rules_x.destination_id = rules_opposite.origin_id)

inner join fare_attributes on rules_x.fare_id = fare_attributes.fare_id
inner join agency on rules_x.agency_id = agency.agency_id
inner join fare_attributes f1 ON rules_opposite.fare_id = f1.fare_id

where rules_x.origin_id IS NOT NULL and rules_x.destination_id IS NOT NULL AND rules_x.route_id IS NULL AND rules_y.route_id IS NULL AND rules_x.contains_id IS NULL AND rules_y.contains_id IS NULL AND rules_y.route_id IS NULL and rules_y.fare_rule_id IS NULL

AND rules_opposite.route_id IS NULL AND rules_opposite.contains_id IS NULL 

order by rules_x.agency_id ASC, price ASC, origin_zone ASC, destination_zone ASC
```

And I believe below shows origin/destination zone based fare rules where the fare is the same in the reverse direction.

```sql
select rules_x.fare_rule_id,rules_x.fare_id,rules_x.origin_id,rules_x.destination_id,rules_x.agency_id,rules_y.fare_rule_id
from fare_rules rules_x
LEFT JOIN fare_rules rules_y
on (rules_x.origin_id = rules_y.destination_id AND rules_x.destination_id = rules_y.origin_id AND rules_x.fare_id = rules_y.fare_id)
where rules_x.origin_id IS NOT NULL and rules_x.destination_id IS NOT NULL AND rules_x.route_id IS NULL AND rules_y.route_id IS NULL AND rules_x.contains_id IS NULL AND rules_y.contains_id IS NULL AND rules_y.route_id IS NULL and rules_y.fare_rule_id IS NOT NULL
order by rules_x.agency_id ASC
```

Note that above queries just return fare rules records that define origin/destination zones only, with NULL contains_id and route_id. Similar queries could be written that look at reversed fare rules that are identical in the contains_id and route_id columns. (Note: JOINS between NULL values don't work.)

I'm not sure exactly what the best way of altering this data on the migrate is -- all SQL, or migrate first and then run some clean up operations (SQL and/or PHP). Happy to game out ideas if you want.

**Comment by antrim** [comment]
Commit 7f12c46d3544feddfa54c7c50edbe2c7693a6d63 adds two new fields to support Wake Robin v1 fare features (see UI sketch, https://docs.google.com/drawings/d/11pgz1Zmr8i04tMHKI13U5uCu8TRYOn47IjngX8O8DwE/edit). The two new fields are fare_rules.reversible and fare_rules.combinable.

Let's focus on **reversible**. When active, this means that an origin/destination zone fare rule is true in reverse order.

So we need to identify these cases during the migration. @ed-g : can you add this?

Below shows fare rules where there is a DIFFERENT reverse direction fare. More at https://3.basecamp.com/3194913/buckets/257018/todos/149854143#__recording_151391437

```sql
select rules_x.fare_rule_id,rules_x.fare_id,rules_x.origin_id,rules_x.destination_id,rules_x.agency_id,agency.agency_name,z1.zone_name AS origin_zone, z2.zone_name AS destination_zone, fare_attributes.price, f1.price as opposite_fare
from fare_rules rules_x
LEFT JOIN fare_rules rules_y
on (rules_x.origin_id = rules_y.destination_id AND rules_x.destination_id = rules_y.origin_id AND rules_x.fare_id = rules_y.fare_id)

INNER JOIN zones z1 ON rules_x.origin_id = z1.zone_id
INNER JOIN zones z2 ON rules_x.destination_id = z2.zone_id

left JOIN fare_rules rules_opposite
ON (rules_x.origin_id = rules_opposite.destination_id AND rules_x.destination_id = rules_opposite.origin_id)

inner join fare_attributes on rules_x.fare_id = fare_attributes.fare_id
inner join agency on rules_x.agency_id = agency.agency_id
inner join fare_attributes f1 ON rules_opposite.fare_id = f1.fare_id

where rules_x.origin_id IS NOT NULL and rules_x.destination_id IS NOT NULL AND rules_x.route_id IS NULL AND rules_y.route_id IS NULL AND rules_x.contains_id IS NULL AND rules_y.contains_id IS NULL AND rules_y.route_id IS NULL and rules_y.fare_rule_id IS NULL

AND rules_opposite.route_id IS NULL AND rules_opposite.contains_id IS NULL 

order by rules_x.agency_id ASC, price ASC, origin_zone ASC, destination_zone ASC
```

And I believe below shows origin/destination zone based fare rules where the fare is the same in the reverse direction.

```sql
select rules_x.fare_rule_id,rules_x.fare_id,rules_x.origin_id,rules_x.destination_id,rules_x.agency_id,rules_y.fare_rule_id
from fare_rules rules_x
LEFT JOIN fare_rules rules_y
on (rules_x.origin_id = rules_y.destination_id AND rules_x.destination_id = rules_y.origin_id AND rules_x.fare_id = rules_y.fare_id)
where rules_x.origin_id IS NOT NULL and rules_x.destination_id IS NOT NULL AND rules_x.route_id IS NULL AND rules_y.route_id IS NULL AND rules_x.contains_id IS NULL AND rules_y.contains_id IS NULL AND rules_y.route_id IS NULL and rules_y.fare_rule_id IS NOT NULL
order by rules_x.agency_id ASC
```

Note that above queries just return fare rules records that define origin/destination zones only, with NULL contains_id and route_id. Similar queries could be written that look at reversed fare rules that are identical in the contains_id and route_id columns. (Note: JOINS between NULL values don't work.)

I'm not sure exactly what the best way of altering this data on the migrate is -- all SQL, or migrate first and then run some clean up operations (SQL and/or PHP). Happy to game out ideas if you want.

**Comment by ed-g** [comment]
Showing agency name. Applying to play_migrate_ tables.

```sql
select agencies.agency_name, rules_x.fare_rule_id, rules_x.fare_id, rules_x.origin_id,
    rules_x.destination_id, rules_x.agency_id, rules_y.fare_rule_id
from play_migrate_fare_rules rules_x
LEFT JOIN play_migrate_fare_rules rules_y
    ON (rules_x.origin_id = rules_y.destination_id 
        AND rules_x.destination_id = rules_y.origin_id 
        AND rules_x.fare_id = rules_y.fare_id)
JOIN play_migrate_agencies agencies 
    ON agencies.agency_id = rules_x.agency_id
where rules_x.origin_id IS NOT NULL 
    and rules_x.destination_id IS NOT NULL 
    AND rules_x.route_id IS NULL 
    AND rules_y.route_id IS NULL 
    AND rules_x.contains_id IS NULL 
    AND rules_y.contains_id IS NULL 
    AND rules_y.route_id IS NULL 
    and rules_y.fare_rule_id IS NOT NULL
order by rules_x.agency_id ASC;
```

**Comment by ed-g** [comment]
New columns are `{migrate}_fare_rules.is_symmetric` and `{migrate}_fare_rules.is_combinable`

**Comment by ed-g** [comment]
There are what appear to be duplicate fare rules, identical except for `fare_rule_id`'s.

Should we delete all but one of each duplicate?

```sql
select fare_id, origin_id, destination_id, count(*)
from play_migrate_fare_rules
where origin_id is not null and destination_id is not null and route_id is null
group by fare_id, origin_id, destination_id
having count(*) > 1 
order by count(*) desc;
```

```sql
┌─────────┬───────────┬────────────────┬───────┐
│ fare_id │ origin_id │ destination_id │ count │
╞═════════╪═══════════╪════════════════╪═══════╡
│     470 │       309 │            315 │     2 │
│     475 │       311 │            306 │     2 │
│     472 │       307 │            309 │     2 │
│     470 │       317 │            311 │     2 │
│     473 │       328 │            306 │     2 │
│     473 │       313 │            307 │     2 │
│     323 │        31 │             37 │     2 │
│     473 │       308 │            311 │     2 │
│     475 │       312 │            314 │     2 │
│     472 │       313 │            308 │     2 │
│     323 │        27 │             37 │     2 │
│     472 │       320 │            317 │     2 │
│     474 │       308 │            312 │     2 │
│     470 │       313 │            320 │     2 │
│     473 │       307 │            317 │     2 │
│     472 │       309 │            311 │     2 │
│     470 │       306 │            316 │     2 │
│     618 │        78 │            371 │     2 │
│     472 │       312 │            328 │     2 │
│     475 │       306 │            311 │     2 │
│     475 │       312 │            307 │     2 │
│     471 │       307 │            306 │     2 │
│     470 │       328 │            309 │     2 │
│     471 │       309 │            310 │     2 │
│     472 │       309 │            307 │     2 │
[...]
│     473 │       320 │            311 │     2 │
└─────────┴───────────┴────────────────┴───────┘
(214 rows)
```

```sql
select * from play_migrate_fare_rules where fare_id = 470 and origin_id = 309 and destination_id = 315;
┌──────────────┬─────────┬──────────┬───────────┬────────────────┬─────────────┬───────────┬──────────────┬───────────────┬─────────────────────┬────────────────┬─────────────────┬──────────────────┬───────────────────────┬────────────────────┐
│ fare_rule_id │ fare_id │ route_id │ origin_id │ destination_id │ contains_id │ agency_id │ is_symmetric │ is_combinable │    last_modified    │ fare_id_import │ route_id_import │ origin_id_import │ destination_id_import │ contains_id_import │
╞══════════════╪═════════╪══════════╪═══════════╪════════════════╪═════════════╪═══════════╪══════════════╪═══════════════╪═════════════════════╪════════════════╪═════════════════╪══════════════════╪═══════════════════════╪════════════════════╡
│         2910 │     470 │          │       309 │            315 │             │        89 │ f            │ t             │ 0001-01-01 00:00:00 │                │                 │                  │                       │                    │
│         3149 │     470 │          │       309 │            315 │             │        89 │ f            │ t             │ 0001-01-01 00:00:00 │                │                 │                  │                       │                    │
└──────────────┴─────────┴──────────┴───────────┴────────────────┴─────────────┴───────────┴──────────────┴───────────────┴─────────────────────┴────────────────┴─────────────────┴──────────────────┴───────────────────────┴────────────────────┘
(2 rows)
```

**Comment by ed-g** [comment]
Ok, I've taken an unusual approach.

views.play_migrate_fare_rules_symmetric  (fare_id integer, zone_id_a integer, zone_id_b integer) is a view with one row for each symmetric pair of rules from play_migrate_fare_rules.

As a tiebreak, since they could in theory occur in either order, zone_id_a is defined to be numerically less than zone_id_b. This sidesteps having multiple entries for each symmetric zone. If this proves inconvenient, this restriction could be lifted without changing the rest of the design; there would simply be twice as many rows in play_migrate_fare_rules_symmetric.

views.play_migrate_fare_rules_symmetric only contains three columns, since the other columns from play_migrate_fare_rules are not necessary: route_id and contains_id are NULL by definition, and fare_rule_id is not needed to uniquely identify a symmetric fare rule (and since multiple fare_rules are represented by each row of play_migrate_fare_rules_symmetric).

If a row is `INSERT`ed into views.play_migrate_fare_rules_symmetric, two corresponding rows are inserted into play_migrate_fare_rules.

If is row is `DELETE`d from views.play_migrate_fare_rules_symmetric, any corresponding rows are deleted from play_migrate_fare_rules.

views.play_migrate_fare_rules_not_symmetric represents the complement of 
views.play_migrate_fare_rules_symmetric, it contains all rows from play_migrate_fare_rules which do not meet our definition of symmetric. Since this is a simple view, rows can be directly `INSERT`ed, `UPDATE`d or `DELETE`d from the view and they'll appear or disappear from play_migrate_fare_rules as the case may be.

The is_symmetric column of play_migrate_fare_rules is set through an UPDATE statement in the migration script. This update could be run automatically whenever the table is modified, if we decide we prefer the column to the view.

```sql
    UPDATE {$table_prefix}_fare_rules
    SET is_symmetric = CASE 
            WHEN fare_rule_id IN 
                 (SELECT fare_rule_id FROM views.{$table_prefix}_fare_rules_asymmetric)
            THEN False
            ELSE True END CASE;
```

**Comment by antrim** [comment]
@ed-g : I can't study this for another several hours, but I did skim, and wanted to provide a quick reaction. My understanding is that fare_rules_symmetric would need to include route_id, and, possibly, contains_id.

Reasoning:

* I think we can call a fare rule **_from zone A to zone B, only on Route 1_** symmetrical to **_from zone B to zone A, only on Route 1_** -- basically, all other fields are the same except start/end reversed.
* Other fields are used for some of these symmetric fare rules. See delnorte-ca-us (Redwood Coast Transit, ID 19) as an example. It sometimes takes me a little bit of thinking to (re-)understand a complicated fare system like that one, but, from memory, if other conditions (route_id, contains_id) are applied in a single fare_rule record, then all of those conditions must be satisfied in a trip for the fare to apply. A bit of investigation in the db should return if there are other cases like delnorte-ca-us.

**Comment by ed-g** [comment]
@antrim I've added route_id and contains_id columns to fare_rules_symmetric. INSERT and DELETE work, UPDATE is not yet implemented but I have an idea for how it would work.

I believe it makes sense to have symmetric fare rules which use contains_id. There are only a few examples in the GTFSManager database, but they seem reasonable to me:

```sql
SELECT * FROM views.play_migrate_fare_rules_symmetric
WHERE contains_id IS NOT NULL;
+-----------+-------------+-------------+------------+---------------+
|   fare_id |   zone_id_a |   zone_id_b |   route_id |   contains_id |
|-----------+-------------+-------------+------------+---------------|
|      1673 |         952 |         955 |     <null> |           953 |
|      1671 |         952 |         955 |     <null> |           953 |
|      1673 |         954 |         955 |     <null> |           953 |
|      1671 |         954 |         955 |     <null> |           953 |
|      1673 |         952 |         954 |     <null> |           953 |
|      1671 |         952 |         954 |     <null> |           953 |
|       224 |         174 |         178 |        298 |           177 |
|      1673 |         953 |         954 |     <null> |           952 |
|      1671 |         953 |         954 |     <null> |           952 |
|       957 |         174 |         177 |        298 |           176 |
+-----------+-------------+-------------+------------+---------------+
SELECT 10
```

I'll plan to add the agency_id to the views.play_migrate_fare_rules_symmetric table to make it a little more convenient.

**Comment by ed-g** [comment]
UPDATE implemented.

**Comment by ed-g** [comment]
718df45 sets is_combinable based on my reading of the output_feeds_commandline.php script.

* All `fare_rules` for Sonoma and Mendocino are `non-combinable`.
* For Redwood Coast:
  1. `fare_rules` which specify neither an origin_id nor a destination_id are `combinable`.
  1. `fare_rules` which specify either an origin_id or a destination_id are `non-combinable`.
