### ISSUE TITLE
Give timed_patterns names

### ISSUE THREAD

**Issue by livemixlove** [trilliumtransit/migrate-GTFS#9]
Should be based on something: maybe deviations from other timed patterns in the same pattern or total duration. @ed-g

**Comment by antrim** [comment]
Should I add any more here?

**Comment by livemixlove** [comment]
Feel free!

**Comment by livemixlove** [comment]
Also note that we should give them "names" not "labels".

**Comment by ed-g** [comment]
Added column (name text).

```sql
> \d+ migrate_timed_patterns
                       Table "public.migrate_timed_patterns"
┌──────────────────┬──────────┬───────────┬──────────┬──────────────┬─────────────┐
│      Column      │   Type   │ Modifiers │ Storage  │ Stats target │ Description │
╞══════════════════╪══════════╪═══════════╪══════════╪══════════════╪═════════════╡
│ agency_id        │ smallint │ not null  │ plain    │              │             │
│ timed_pattern_id │ bigint   │ not null  │ plain    │              │             │
│ pattern_id       │ bigint   │ not null  │ plain    │              │             │
│ name             │ text     │           │ extended │              │             │
└──────────────────┴──────────┴───────────┴──────────┴──────────────┴─────────────┘
```

**Comment by ed-g** [comment]
The timed_pattern_id should be a SERIAL primary key, shouldn't it?

**Comment by antrim** [comment]
We don't have have a way of naming patterns yet. So I opened #11 for consideration.

It strikes me that:
* two timed patterns with the same trip duration for a single pattern would be exceedingly rare
* there isn't really going to be a good way of automatically naming timed patterns, other than using trip duration as a label

So, I propose:
* No migrated names for timed patterns
* Users can add labels later if they find it useful
* Wake Robin UI shows trip duration to distinguish timed patterns
